### ISSUE TITLE
This also captures the clicking on links

### ISSUE THREAD

**Issue by noppelmax** [Vinno97/evince-synctex#5]
Hey Vinno,

thanks for the script! I do have one problem with it, tough. I also captures the clicking on links some how. Ctrl+leftMouse on a link in a pdf lead to the respective latex line instead to the url (zotero in my case). Do you have any idea how to fix it? And do you also have this problem?

Kind regards,
Max

**Comment by Vinno97** [comment]
Hi Max, 
That's an interesting question. I'm pretty sure there's nothing I can do about this, however, and that this behavior is out of the control of this script. All it does is wait for whenever Evince sends a message requesting the editor to be synced up to the viewer.

I believe the hyperlinks that SyncTex codes hyperlinks into the PDF are almost identical to standard hyperlinks. I suspect that the link text in your document then has two overlapping link boxes, of which Evince decides to choose the SyncTex link over the other one. Do other editors not have this issue? Perhaps the Evince folks can  be more helpful
